# Import Statements (libraries + Functions)

In [1]:
import numpy as np
import pandas as pd
import vcf
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

%matplotlib inline

In [2]:
#import sklearn

In [3]:
import scipy.stats
import scipy.stats as stats
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import spearmanr
from scipy.stats import ranksums

In [4]:
#from Bio import SeqIO

In [5]:
#import io

In [6]:
import json

In [7]:
# import screed
# import mmh3

In [8]:
#import subprocess

In [9]:
#from pycirclize import Circos

In [10]:
from matplotlib.patches import Patch
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrowPatch
import matplotlib.ticker as mticker

In [11]:
# Define matplotlib plot style from config file
plt.style.use('../mgm.v1.mplstyle')

In [12]:
import matplotlib
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42

In [13]:
# https://bioframe.readthedocs.io/en/latest/guide-intervalops.html
import bioframe as bf
#import bioframe.vis

#### Define sets of coord cols for using BioFrame

In [14]:
Query_CoordCols = ("Query_Name", "Query_Start", "Query_End")
HmReg_CoordCols = ("Chr", "Start", "End")
HmRegion_CoordCols = HmReg_CoordCols
Epitope_CoordCols = ("Chrom", "Rv_Start", "Rv_End")
RE_CoordCols = ("seqname", "start_0based", "end_1based")
GenomeAnno_CoordCols = ("Chrom", "Start", "End")

#### Pandas Viewing Settings

In [15]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# Parse `Mtb151CI` Isolate Metadata

In [17]:
Repo_DataDir = "../../Data"
InputAsmPath_Dir = f"{Repo_DataDir}/231121.InputAsmTSVs.MtbSetV3.151CI"

MtbSetV3_151CI_InputAsmPATHs_TSV = f"{InputAsmPath_Dir}/231121.MtbSetV3.151CI.HybridAndSRAsm.FAPATHs.V1.tsv"
MtbSetV3_151CI_AsmSumm_TSV = f"{InputAsmPath_Dir}/231121.MtbSetV3.151CI.HybridAsm.AsmSummary.V2.tsv"

### Reading in "WGA151CI_AsmSummary_DF"

In [18]:
WGA151CI_AsmSummary_DF = pd.read_csv(MtbSetV3_151CI_AsmSumm_TSV, sep = "\t")

SampleIDs_151CI_SOI = list( WGA151CI_AsmSummary_DF["SampleID"].values )
WGA151CI_SampleIDs = SampleIDs_151CI_SOI
WGA151CI_AsmSummary_DF.shape

(151, 7)

#### Create SampleID Mapping Dicts

In [19]:
WGA151CI_ID_To_PrimLineage_Dict = dict(WGA151CI_AsmSummary_DF[['SampleID', 'PrimaryLineage']].values)
WGA151CI_ID_To_SubLineage_Dict = dict( WGA151CI_AsmSummary_DF[["SampleID", "Lineage"]].values)
WGA151CI_ID_To_Dataset_Dict = dict(WGA151CI_AsmSummary_DF[['SampleID', 'Dataset_Tag']].values)  
ID_To_PrimLineage_Dict = dict(WGA151CI_AsmSummary_DF[['SampleID', 'PrimaryLineage']].values)
ID_To_SubLineage_Dict = dict( WGA151CI_AsmSummary_DF[["SampleID", "Lineage"]].values)
ID_To_Dataset_Dict = dict(WGA151CI_AsmSummary_DF[['SampleID', 'Dataset_Tag']].values)

# Import/parse processed H37rv genome annotations

In [20]:
RepoRef_Dir = "../../References"

AnnotatedGenes_And_IntergenicRegions_RepoRef_Dir = f"{RepoRef_Dir}/201027_H37rv_AnnotatedGenes_And_IntergenicRegions"
H37Rv_GenomeAnnotations_Genes_TSV = f"{AnnotatedGenes_And_IntergenicRegions_RepoRef_Dir}/H37Rv_GenomeAnnotations.Genes.tsv"

## H37Rv Gene Annotations TSV
H37Rv_GenomeAnno_Genes_DF = pd.read_csv(H37Rv_GenomeAnnotations_Genes_TSV, sep = "\t")
H37Rv_GeneInfo_Subset_DF = H37Rv_GenomeAnno_Genes_DF[["H37rv_GeneID", "Symbol", "Feature", "Functional_Category", "Is_Pseudogene", "Product", "PEandPPE_Subfamily", "ExcludedGroup_Category"]]

RvID_To_Symbol_Dict = dict(H37Rv_GenomeAnno_Genes_DF[['H37rv_GeneID', 'Symbol']].values)
Symbol_To_RvID_Dict = dict(H37Rv_GenomeAnno_Genes_DF[['Symbol', 'H37rv_GeneID']].values)
Symbol_To_FuncCat_Dict = dict(H37Rv_GenomeAnno_Genes_DF[['Symbol', 'Functional_Category']].values)

ESX_Genes_List_TSV = f"{RepoRef_Dir}/190927_H37rv_ListOf_ESXgenes.tsv"
Esx_Genes_DF = pd.read_csv(ESX_Genes_List_TSV, sep = '\t')

In [21]:
H37Rv_GenomeAnno_Genes_DF.head(1)

         Chrom  Start   End Strand H37rv_GeneID Symbol Feature   Functional_Category Is_Pseudogene                                         Product PEandPPE_Subfamily ExcludedGroup_Category
0  NC_000962.3      0  1524      +       Rv0001   dnaA     CDS  information pathways            No  Chromosomal replication initiator protein DnaA                NaN            NotExcluded

### Parse the WHO AR Variant Catalog (Mtb)

In [22]:
WHO_ResVar_DF = pd.read_csv("../../References/WHO_MtbAMR_Catalog/WHO_resistance_variants_all.csv", sep =",")
WHO_ResVar_LVL1_DF = WHO_ResVar_DF[ WHO_ResVar_DF["confidence"] == '1) Assoc w R']
WHO_ResVar_DF.shape

(17419, 5)

In [23]:
WHO_ResVar_LVL1_DF.shape

(201, 5)

In [24]:
WHO_ConfResGenes = list(WHO_ResVar_LVL1_DF["gene"].unique())
print(len(WHO_ConfResGenes))
print( WHO_ConfResGenes )

15
['inhA', 'rrs', 'eis', 'tlyA', 'embB', 'embA', 'ethA', 'katG', 'gyrA', 'rplC', 'gyrB', 'pncA', 'rpoB', 'rpsL', 'gid']

# Parse in H37Rv Homology-Map Results (k19w19)

### Define all HmMap file paths

In [25]:
Main_Project_Dir = "/n/data1/hms/dbmi/farhat/mm774/Projects/Mtb_WGA_Analysis_V9"

H37_Rv_MM2_HomologyMapping_Dir = f"{Main_Project_Dir}/250901.H37Rv.HomologyMapping.k19w19.ProcessedData.V2"

# Define paths to output TSVS

### Homologous regions (MERGED)
RvHmMap_Merged_ParaRegions_TSV  = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.MergedRegions.ParalogousRegions.k19w19.tsv"
RvHmMap_Merged_LocalRepeats_TSV = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.MergedRegions.LocalRepeats.k19w19.tsv"

### Homology map (pairwise alignments)
RvHmMap_Aln_All_TSV           = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.k19w19.Aln.All.tsv"
RvHmMap_Aln_PRs_NoOverlap_TSV = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.k19w19.Aln.NoOverlap.tsv"
RvHmMap_Aln_LRs_WiOverlap_TSV = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.k19w19.Aln.WiOverlap.tsv"

RvHmMap_Aln_PRs_NoOverlap_Clustered_TSV     = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.k19w19.Aln.NoOverlap.Clustered.tsv"
RvHmMap_Aln_LRs_WiOverlap_Clustered_TSV     = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.k19w19.Aln.OnlyOverlap.Clustered.tsv"

### Variants from the homology map alignments
RvHmMap_Var_TSV      = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.k19w19.variants.tsv"
RvHmMap_Var_SNPs_TSV = f"{H37_Rv_MM2_HomologyMapping_Dir}/RvHmMap.k19w19.variants.snps.tsv"

### Parse in HmRegions (`Paralogous_Regions` and `Local_Repeats`)

In [26]:
HmMapRegs_ParaRegs_k19w19_DF = pd.read_csv(RvHmMap_Merged_ParaRegions_TSV,
                                    sep="\t")
#HmMapRegs_ParaRegs_k19w19_DF["Overlap_Genes"] = HmMapRegs_ParaRegs_k19w19_DF["Overlap_Genes"].fillna("_")

HmMapRegs_ParaRegs_k19w19_DF.shape

(200, 13)

In [27]:
Rv_HHR_DF = HmMapRegs_ParaRegs_k19w19_DF
Rv_HHR_DF.shape

(200, 13)

In [28]:
HmMapRegs_LocalRepeats_k19w19_DF = pd.read_csv(RvHmMap_Merged_LocalRepeats_TSV, 
                                        sep="\t")

#HmMapRegs_LocalRepeats_k19w19_DF["Overlap_Genes"] = HmMapRegs_LocalRepeats_k19w19_DF["Overlap_Genes"].fillna("_")

HmMapRegs_LocalRepeats_k19w19_DF.shape

(50, 13)

In [29]:
HmMapRegs_All_LRsPRs_K19w19_DF = pd.concat([HmMapRegs_ParaRegs_k19w19_DF,
                                            HmMapRegs_LocalRepeats_k19w19_DF])

HmMapRegs_All_LRsPRs_K19w19_DF.shape

(250, 13)

In [30]:
HmMapRegs_ParaRegs_k19w19_DF.head(2)

   HmRegion_Num          Chr  Start    End   Center  Length  Overlap_Genes  NOvrlap_Transposase  num_HmAln_All  num_HmAln_PR_BelowSeqID100  num_HmAln_PR_MinSeqID99  HmRegionNum       HmRegionID
0             0  NC_000962.3  80184  80523  80353.5     339         Rv0071                    0              1                           1                        1            0  PR_HmRegion_000
1             1  NC_000962.3  80623  82664  81643.5    2041  Rv0072,Rv0073                    0              1                           1                        1            1  PR_HmRegion_001

#### Peak at head of each HmMap Regions DFs

In [31]:
HmMapRegs_ParaRegs_k19w19_DF.head()

   HmRegion_Num          Chr   Start     End    Center  Length    Overlap_Genes  NOvrlap_Transposase  num_HmAln_All  num_HmAln_PR_BelowSeqID100  num_HmAln_PR_MinSeqID99  HmRegionNum       HmRegionID
0             0  NC_000962.3   80184   80523   80353.5     339           Rv0071                    0              1                           1                        1            0  PR_HmRegion_000
1             1  NC_000962.3   80623   82664   81643.5    2041    Rv0072,Rv0073                    0              1                           1                        1            1  PR_HmRegion_001
2             2  NC_000962.3  103705  105130  104417.5    1425  Rv0094c,Rv0095c                    0              2                           2                        2            2  PR_HmRegion_002
3             3  NC_000962.3  149571  149808  149689.5     237         PE_PGRS2                    0              1                           1                        1            3  PR_HmRegion_003
4             4  NC_000962.3  177203  177447  177325.0     244                _                    0              1                           1                        1            4  PR_HmRegion_004

In [32]:
HmMapRegs_LocalRepeats_k19w19_DF.head()

   HmRegion_Num          Chr   Start     End    Center  Length                                      Overlap_Genes  NOvrlap_Transposase  num_HmAln_All  num_HmAln_PR_BelowSeqID100  num_HmAln_PR_MinSeqID99  HmRegionNum       HmRegionID
0             0  NC_000962.3  333811  335879  334845.0    2068                                           PE_PGRS3                    0              1                           1                        1            0  LR_HmRegion_000
1             1  NC_000962.3  366430  375121  370775.5    8691                                          PPE5,PPE6                    0              6                           6                        6            1  LR_HmRegion_001
2             2  NC_000962.3  424011  432951  428481.0    8940                                     hspR,PPE7,PPE8                    0              5                           4                        4            2  LR_HmRegion_002
3             3  NC_000962.3  566288  580814  573551.0   14526  hbhA,Rv0476,Rv0477,deoC,Rv0479c,Rv0480c,Rv0481...                    0              4                           2                        1            3  LR_HmRegion_003
4             4  NC_000962.3  631298  631436  631367.0     138                                             Rv0538                    0              2                           2                        2            4  LR_HmRegion_004

### Parse in homology-map DFs (pairwise alignments between all homologous regions)

In [33]:
HmMap_Aln_k19w19_DF = pd.read_csv(RvHmMap_Aln_All_TSV,
                           sep="\t")
HmMap_Aln_k19w19_DF.shape

(776, 24)

In [34]:
HmMap_Aln_k19w19_NoOverlap_DF = pd.read_csv(RvHmMap_Aln_PRs_NoOverlap_Clustered_TSV,
                                     sep="\t")
HmMap_Aln_k19w19_NoOverlap_DF.shape

(640, 34)

In [35]:
HmMap_Aln_k19w19_LocalRepeat_DF = pd.read_csv(RvHmMap_Aln_LRs_WiOverlap_Clustered_TSV,
                                              sep="\t")
HmMap_Aln_k19w19_LocalRepeat_DF.shape

(136, 34)

In [36]:
HmMap_Aln_PR_ExactCopy_DF = HmMap_Aln_k19w19_NoOverlap_DF.query("SeqID == 1.0")
print(HmMap_Aln_PR_ExactCopy_DF.shape)

(255, 34)

In [37]:
HmMap_Aln_PR_NoPerfAln_DF = HmMap_Aln_k19w19_NoOverlap_DF.query("SeqID != 1.0")
print(HmMap_Aln_PR_NoPerfAln_DF.shape)

(385, 34)

In [38]:

HmMap_Aln_PR_MaxSeqID99_DF = HmMap_Aln_k19w19_NoOverlap_DF.query("SeqID <= 0.99")
print(HmMap_Aln_PR_MaxSeqID99_DF.shape)

(331, 34)

### Parse in HomologyMap Alignment Variants DFs

In [39]:
Mtb_HM_Var_DF = pd.read_csv(RvHmMap_Var_TSV, sep="\t")
Mtb_HM_Var_SNPs_DF = pd.read_csv(RvHmMap_Var_SNPs_TSV, sep="\t")

In [40]:
# Build trimmed + unique HM SNPs DF
UnqSNPs_TarCol = ['Query_Name', 'Query_Start', 'Query_End', 'Ref', 'Alt', 'SNP']

HM_Var_SNPs_TrimUnq_DF = Mtb_HM_Var_SNPs_DF[UnqSNPs_TarCol].drop_duplicates()
HM_Var_SNPs_TrimUnq_DF.shape

(51590, 6)

In [41]:
Mtb_HM_Var_DF.shape

(79508, 13)

In [42]:
Mtb_HM_Var_SNPs_DF.shape

(65617, 13)

# Parse curated TB antigens + epitopes (T-cell, CD4+)
Source Datasets: (Panda-24, Lindestam-16)

In [26]:
Repo_Epitope_MainDir = "../../Data/220813_MtbEpitopes"

#LPM_AllAssayedPeptides_Mapped_TSV = f"{Repo_Epitope_MainDir}/240820.Panda24_Lind16.Merged.PeptidesMappedToRv.AllAssayed.V1.tsv" 
Lind16_Peptides_HLAInfo_TSV = f"{Repo_Epitope_MainDir}/240815.Lindestram2016.HLA_ResponseInfo.V1.tsv" 

LPM_AllAssayedPeptides_WiMutInfo_TSV = f"{Repo_Epitope_MainDir}/240820.Panda24_Lind16.Merged.PeptidesMappedToRv.All.AnnoByMutFreq.V2.tsv" 

Rv_Genes_Epitope_SummStats_TSV = f"{Repo_Epitope_MainDir}/240820.RvGene.EpitopeMappingStats.V1.tsv"

In [27]:
!du -sh $Rv_Genes_Epitope_SummStats_TSV $LPM_AllAssayedPeptides_WiMutInfo_TSV

615K	../../Data/220813_MtbEpitopes/240820.RvGene.EpitopeMappingStats.V1.tsv
3.7M	../../Data/220813_MtbEpitopes/240820.Panda24_Lind16.Merged.PeptidesMappedToRv.All.AnnoByMutFreq.V2.tsv

### Parse in DF of all epitope mapping results (all assayed peptides, N = `18741`)

In [28]:
LPM_AllPep_V2_DF = pd.read_csv(LPM_AllAssayedPeptides_WiMutInfo_TSV, sep = "\t")
LPM_AllPep_V2_DF["Reactivity"] = LPM_AllPep_V2_DF["PosEpitope_Any"].replace(True, "Positive").replace(False, "Negative")
LPM_AllPep_V2_DF.shape

(18741, 31)

In [29]:
LPM_AllPep_V2_DF.columns

Index(['Epitope_ID', 'Epitope_Seq', 'Epitope_Len', 'RvID', 'Symbol', 'AA_Start', 'AA_End', 'Chrom', 'Rv_Start', 'Rv_End', 'EpitopeSeqFreqInAntigen', 'Dataset', 'Assayed_Panda24', 'PosEpitope_Panda24', 'Assayed_Lindestam16', 'PosEpitope_Lindestam16', 'PosEpitope_Any', 'EpitopeSymbol_ID', 'N_HmRegion', 'HasHmRegion', 'Antigen_LVL2', 'N_NSMut_Total', 'N_NSMut_mGCE', 'IsMutBymGCE', 'N_NSMut_pGCE', 'IsMutBypGCE', 'N_mGCEs_WiNS', 'WiNS_mGC_EventIDs', 'N_pGCEs_WiNS', 'WiNS_pGC_EventIDs', 'Reactivity'], dtype='object')

### Subset DF for only POSITIVE EPITOPES or NEGATIVE PEPTIDES

In [30]:
LPM_AllPep_V2_DF.shape

(18741, 31)

In [31]:
LPM_PosEpi_V2_DF = LPM_AllPep_V2_DF.query("PosEpitope_Any == True")
LPM_PosEpi_V2_DF.shape

(424, 31)

In [32]:
LPM_PosEpi_InL2Antigen_V2_DF = LPM_PosEpi_V2_DF.query("Antigen_LVL2 == True")
LPM_PosEpi_InL2Antigen_V2_DF.shape

(342, 31)

In [33]:
LPM_NegPep_V2_DF = LPM_AllPep_V2_DF.query("PosEpitope_Any == False")
LPM_NegPep_V2_DF.shape

(18317, 31)

## Parse gene-level epitope mapping summary for all H37Rv genes

In [34]:
Rv_Genes_EpitopeSummary_DF = pd.read_csv(Rv_Genes_Epitope_SummStats_TSV, sep="\t")
Rv_Genes_EpitopeSummary_DF.shape

(3841, 20)

In [35]:
Rv_Genes_EpitopeSummary_DF.head()

         Chrom  Start   End Strand Feature H37rv_GeneID  Symbol      Functional_Category              Gene_Cat_V2  N_Pos  N_Neg  Total  Positive_Proportion  Middle  Length  AnyPosEpitope  Antigen_LVL2  N_HmRegion  HasHmRegion AntigenLVL2_And_HHR_Comb
0  NC_000962.3      0  1524      +     CDS       Rv0001    dnaA     information pathways     information pathways      0      8      8                  0.0   762.0    1524          False         False           0        False          NonReactive-Unq
1  NC_000962.3   2051  3260      +     CDS       Rv0002    dnaN     information pathways     information pathways      0      6      6                  0.0  2655.5    1209          False         False           0        False          NonReactive-Unq
2  NC_000962.3   3279  4437      +     CDS       Rv0003    recF     information pathways     information pathways      0      6      6                  0.0  3858.0    1158          False         False           0        False          NonReactive-Unq
3  NC_000962.3   4433  4997      +     CDS       Rv0004  Rv0004  conserved hypotheticals  conserved hypotheticals      0      3      3                  0.0  4715.0     564          False         False           0        False          NonReactive-Unq
4  NC_000962.3   5239  7267      +     CDS       Rv0005    gyrB     information pathways     information pathways      0      8      8                  0.0  6253.0    2028          False         False           0        False          NonReactive-Unq

# Parse gene-level epitope + mutation + GCE stats - (antigen/epitope info, GCE info, Mutational Burden, etc)

In [36]:
Repo_AntigenMut_MainDir = "../../Data/250609.AntigenMutationalBurdenAnalysis"

Rv_Gene_MutStats_V1_TSV     = f"{Repo_AntigenMut_MainDir}/250808.RvGenes.GCE.MutationFreq.Epitopes.SummaryStats.V1.tsv"

Rv_Antigens_MutStats_V1_TSV = f"{Repo_AntigenMut_MainDir}/250808.RvL2Antigens.GCE.MutationFreq.Epitopes.SummaryStats.V1.tsv"

PerRvPosition_EpitopeCovStats_TSV = f"{Repo_AntigenMut_MainDir}/250609.PerRvPos.EpitopeCoverage.AssayedPosOnly.V1.tsv.gz"

PerRvCodon_MutationFreq_TSV = f"{Repo_AntigenMut_MainDir}/250609.PerRvCodon.MissenseMutatationFreq.V1.tsv.gz"

### a) Parse gene-level - mutational burden and epitope mapping summary DFs

In [37]:
Genes_GCandMutFreqStats_DF = pd.read_csv(Rv_Gene_MutStats_V1_TSV,
                                           sep = "\t")

Genes_GCandMutFreqStats_DF.shape

(3841, 36)

In [38]:
Antigen_GCandMutFreqStats_DF = pd.read_csv(Rv_Antigens_MutStats_V1_TSV,
                                           sep = "\t")

Antigen_GCandMutFreqStats_DF.shape

(53, 38)

In [39]:
# Antigen_GCandMutFreqStats_DF = Genes_GCandMutFreqStats_DF.query("Antigen_LVL2 == True")
# Antigen_GCandMutFreqStats_DF.shape

In [40]:
Antigen_GCandMutFreqStats_DF.head()

         Chrom    Start      End Strand Feature H37rv_GeneID Symbol           Functional_Category Gene_Cat_V2  N_Pos  N_Neg  Total  Positive_Proportion     Middle  Length  AnyPosEpitope  Antigen_LVL2  N_HmRegion  HasHmRegion AntigenLVL2_And_HHR_Comb  pGCE_Ovrlap  mGCE_Ovrlap  Total_NS_Muts  Total_NS_Muts_InEpitope  Total_NS_Muts_BymGCE  Total_NS_Muts_BypGCE  Total_NS_Muts_BymGCE_InEpitope  Total_NS_Muts_BypGCE_InEpitope  RelFreq_NS_Muts  RelFreq_NS_Mut_InEpitope  Has_mGCE  Has_mGCE_WiNSMut  Has_mGCE_WiNSMut_InEpitope  Has_pGCE  Has_pGCE_WiNSMut  Has_pGCE_WiNSMut_InEpitope  Length_WiPosEpitope  RelLength_WiPosEpitope
0  NC_000962.3  3894425  3895607      +     CDS       Rv3478  PPE60                        PE/PPE      PE/PPE      5     15     20             0.250000  3895016.0    1182           True          True           1         True              Antigen-HHR            8            8          141.0                     24.0                 120.0                 120.0                           120.0                           120.0        35.786802                  6.091371      True              True                        True      True              True                        True                  165                0.139594
1  NC_000962.3  1341005  1341290      +     CDS       Rv1198   esxL  cell wall and cell processes         esx      9      7     16             0.562500  1341147.5     285           True          True           1         True              Antigen-HHR           10            7           30.0                     27.0                  13.0                  20.0                            13.0                            20.0        31.578947                 28.421053      True              True                        True      True              True                        True                  225                0.789474
2  NC_000962.3  2626222  2626519      -     CDS      Rv2347c   esxP  cell wall and cell processes         esx     10      6     16             0.625000  2626370.5     297           True          True           1         True              Antigen-HHR            9            9           17.0                      2.0                  12.0                  12.0                            12.0                            12.0        17.171717                  2.020202      True              True                        True      True              True                        True                  210                0.707071
3  NC_000962.3  1339348  1340524      +     CDS       Rv1196  PPE18                        PE/PPE      PE/PPE     27     56     83             0.325301  1339936.0    1176           True          True           2         True              Antigen-HHR            8            7           61.0                     44.0                  45.0                  46.0                            45.0                            46.0        15.561224                 11.224490      True              True                        True      True              True                        True                  705                0.599490
4  NC_000962.3  1532442  1533633      -     CDS      Rv1361c  PPE19                        PE/PPE      PE/PPE     16     21     37             0.432432  1533037.5    1191           True          True           1         True              Antigen-HHR            5            5           61.0                      9.0                  36.0                  36.0                            36.0                            36.0        15.365239                  2.267003      True              True                        True      True              True                        True                  390                0.327456

In [41]:
Antigen_GCandMutFreqStats_DF["Length"].sum()

48474

### b) Parse Per Codon Position Mutation Freq (Across Gubbins ASR SNP Events) + Epitope mapping coverage DFs

In [42]:
RvPerCodon_NSMutFreq_DF = pd.read_csv(PerRvCodon_MutationFreq_TSV,
                                  sep = "\t")
RvPerCodon_NSMutFreq_DF.shape

(12132, 4)

In [43]:
RvPerCodon_NSMutFreq_DF.head(1)

    Symbol  Codon  Mutation_Count  Pos_0based
0  35kd_ag  230.0               1     3057374

### c) Parse Per Genome Position  Epitope mapping coverage DF

In [44]:
Rv_EpitopeCov_NonZero_DF = pd.read_csv(PerRvPosition_EpitopeCovStats_TSV,
                                  sep = "\t")

Rv_EpitopeCov_NonZero_DF.shape

(746901, 5)

In [45]:
Rv_EpitopeCov_NonZero_DF.head(2)

         chrom  start  end  Cov_PosEpitopes  Cov_AssayedPeptides
0  NC_000962.3    537  538                0                    1
1  NC_000962.3    538  539                0                    1

# Parse `Mtb151CI` Gubbins Results

### Define dictionary of file paths for Gubbins analysis

In [46]:
AnalysisName = "250901.WGA151CI.V9"

Main_Project_Dir = "/n/data1/hms/dbmi/farhat/mm774/Projects/Mtb_WGA_Analysis_V9"

Target_Output_Dir = f"{Main_Project_Dir}/{AnalysisName}"

WGA151_Gubbins_V1_OutputDir = f"{Target_Output_Dir}/Gubbins_v321_ExtSearch_SW_MS4_mpileup_SNVs_10AmbThresh"

Gubbins_V1_OutputDir = WGA151_Gubbins_V1_OutputDir

WGA151_Gubbins_OutPrefix = "Gubbins"

WGA151_Gubbins_FullPrefix_PATH  = f"{WGA151_Gubbins_V1_OutputDir}/{WGA151_Gubbins_OutPrefix}"

WGA151_Gubbins_FilePath_Dict = {}

WGA151_Gubbins_FilePath_Dict["NodeLabelledTree_PATH"]           = f"{WGA151_Gubbins_FullPrefix_PATH}.node_labelled.final_tree.tre"
WGA151_Gubbins_FilePath_Dict["NodeToPriLineage_Dict_JSON"]      = f"{WGA151_Gubbins_FullPrefix_PATH}.NodeToPrimaryLineage.json"
WGA151_Gubbins_FilePath_Dict["BranchStats_CSV"]                 = f"{WGA151_Gubbins_FullPrefix_PATH}.per_branch_statistics.csv"
WGA151_Gubbins_FilePath_Dict["BranchStats_WithLineage_CSV"]     = f"{WGA151_Gubbins_FullPrefix_PATH}.per_branch_statistics.WithLineagePerNode.tsv"
WGA151_Gubbins_FilePath_Dict["EventsPer_1kb_H37Rv_TSV"]         = f"{WGA151_Gubbins_FullPrefix_PATH}.H37Rv.EventsPer1kb.tsv"
WGA151_Gubbins_FilePath_Dict["EventsPer_Gene_H37Rv_TSV"]        = f"{WGA151_Gubbins_FullPrefix_PATH}.H37Rv.EventsPerGene.tsv"
WGA151_Gubbins_FilePath_Dict["EventsPer_HHR_H37Rv_TSV"]         = f"{WGA151_Gubbins_FullPrefix_PATH}.H37Rv.EventsPerMergedHomologousRegion.tsv"

WGA151_Gubbins_FilePath_Dict["RecombPred_Anno_TSV"]             = f"{WGA151_Gubbins_FullPrefix_PATH}.recombination_predictions.Anno.tsv"
WGA151_Gubbins_FilePath_Dict["BaseAncRec_All_TSV"]              = f"{WGA151_Gubbins_FullPrefix_PATH}.branch_base_reconstruction.AnnoByEvent.All.tsv"  
WGA151_Gubbins_FilePath_Dict["BaseAncRec_EventsOnly_TSV"]       = f"{WGA151_Gubbins_FullPrefix_PATH}.branch_base_reconstruction.AnnoByEvent.EventSNPsOnly.tsv" 

WGA151_Gubbins_FilePath_Dict["ASR_SNPs_Anno_V2_All_TSV"]        = f"{WGA151_Gubbins_FullPrefix_PATH}.SNPs.AnnoByEvent.AnnoByCDSEffect.All.tsv"
WGA151_Gubbins_FilePath_Dict["ASR_SNPs_Anno_V2_EventsOnly_TSV"] = f"{WGA151_Gubbins_FullPrefix_PATH}.SNPs.AnnoByEvent.AnnoByCDSEffect.EventSNPsOnly.tsv"

WGA151_Gubbins_FilePath_Dict["BaseAncRec_All_WiCDS_Epitope_Info_TSV"] = f"{WGA151_Gubbins_FullPrefix_PATH}.SNPs.AnnoByEvent.AnnoByCDSandEpitope.All.V2.tsv"  


RecombPreds_Anno_ByHmMatch_ByEpiMut_V3_TSV = f"{Gubbins_V1_OutputDir}/Gubbins.All_GCEs.AnnoBy.EpitopeEffect.V3.tsv"

WGA151_Gubbins_FilePath_Dict["GCEvents.AnnoByHmMatch.AnnoByEpitopeEffect.V3"] = RecombPreds_Anno_ByHmMatch_ByEpiMut_V3_TSV



######### Add Event to Paralog Mapping Results File Paths ##########

EventMapping_ResultsDir = f"{Target_Output_Dir}/RecombEvent-To-HmRegion-Comparison-V3"

GRE_Anno_ByTopHomologMatch_TSV              = f"{EventMapping_ResultsDir}/GubbinsEvents.WiParalogMapping.V1.tsv"
EventMappingToAllParalogs_Info_TSV_PATH     = f"{EventMapping_ResultsDir}/EventMapping.EventsToAllHmRegions.SeqComparisonInfo.tsv"
Pickle_PATH_dictOf_EventAndHomolog_KmerComp = f"{EventMapping_ResultsDir}/EventMapping.DictOf.KmerComparisons.pickle"   


WGA151_Gubbins_FilePath_Dict["GCEvents_WiParalogMapInfo_TSV"]       = GRE_Anno_ByTopHomologMatch_TSV
WGA151_Gubbins_FilePath_Dict["EventMappingToAllParalogs_TSV"]       = EventMappingToAllParalogs_Info_TSV_PATH
WGA151_Gubbins_FilePath_Dict["EventKmerAnalysis_Dict_PicklePath"]   = Pickle_PATH_dictOf_EventAndHomolog_KmerComp

HmRegions_MappedEvents_TSV = f"{EventMapping_ResultsDir}/GCE.Stats.PerMergedHmRegion.PRs.tsv"
HmPairs_MappedEvents_TSV   = f"{EventMapping_ResultsDir}/GCE.Stats.PerPairwiseAln.PRs.tsv"

WGA151_Gubbins_FilePath_Dict["MergedHmRegion_PRs_GCE_Stats_TSV"] = HmRegions_MappedEvents_TSV
WGA151_Gubbins_FilePath_Dict["HmMapAln_PRs_GCE_Stats_TSV"]       = HmPairs_MappedEvents_TSV

####################################################################

## Parse Gene Conv Event Info (pGCEs + mGCEs)

In [47]:
pGCE_DF = pd.read_csv(WGA151_Gubbins_FilePath_Dict["GCEvents.AnnoByHmMatch.AnnoByEpitopeEffect.V3"],
                         sep = "\t")

pGCE_DF.shape

(324, 46)

In [48]:
pGCE_EventIDs = pGCE_DF["EventID"].unique()
len(pGCE_EventIDs)

324

#### Filter All putative GC events to MAPPED GC events

In [49]:
mGCE_DF = pGCE_DF.query("(Max_KmerMatch_ToHm > 0.5)")
mGCE_DF.shape

(213, 46)

In [50]:
mGCE_EventIDs = mGCE_DF["EventID"].unique()
len(mGCE_EventIDs)

213

In [51]:
pGCE_DF.head(1)

       seqname   source feature  start_1based  end_1based  score strand Parent_Node Child_Node  neg_log_likelihood  snp_count                                          taxa_List  start_0based Lineage  CenterOfRegion    Overlap_Genes Overlap_Gene_RvIDs  Contains_Esx  Contains_PEPPE  Contains_REP13E12  NoOverlap_Wi_PEPPE_Esx_13E12_Genes    EventID  EventLen  IsTermNode  NumHmTargets  NumHm_AtMaxKmerMatch                        Top_KmerMatch_HomologTarIDs   Top_KmerMatch_HomologGeneIDs  Max_KmerMatch_ToHm  DistToHm_TopKmatch  TotalKmers_Eval  NumHm_AtMaxSNPMatch                         Top_SNPMatch_HomologTarIDs    Top_SNPMatch_HomologGeneIDs  Max_SNPMatch_ToHm  DistToHm_TopSNPmatch  Freq_SNP_FoundInAnyPR  MaxJC_ToAnyRvGene          GeneIDs_MaxJC  NGenesIDs_MaxJC  NUnqHashes_Event  Overlap_WiAntigenLVL2Gene  N_NS_Mut  N_EpiMutated_By_GCE  N_NegPepMutated_By_GCE EpitopeIDs_NSMutByEvent
0  NC_000962.3  GUBBINS     CDS        103600      104478    0.0      .    Node_148   Node_133         1737.432787         10  ['mada_2-31', 'mada_1-41', 'MT_0080', 'mada_10...        103599     NaN        104038.5  Rv0093c,Rv0094c    Rv0093c,Rv0094c         False           False               True                               False  Event_001       879       False             2                     2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467              0.8608                 NaN               79                    2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467                0.0                   NaN                    0.0             0.8608  ['Rv3467', 'Rv0094c']              2.0              79.0                      False         0                    0                       0                       .

### Parse Gubbins GC events counted over regions of varying resolutions

#### H37Rv - "1 kb windows"

In [52]:
GCE_Per1kb_Stats_DF = pd.read_csv(WGA151_Gubbins_FilePath_Dict["EventsPer_1kb_H37Rv_TSV"], sep = "\t")
GCE_Per1kb_Stats_DF.shape

(4412, 7)

#### H37Rv - Per Gene

In [53]:
GCE_PerGene_Stats_DF = pd.read_csv(WGA151_Gubbins_FilePath_Dict["EventsPer_Gene_H37Rv_TSV"], sep = "\t")
GCE_PerGene_Stats_DF.shape

(4079, 14)

In [54]:
GCE_PerGene_Stats_Atleast1_DF = GCE_PerGene_Stats_DF.query("pGCE_Count > 0")
GCE_PerGene_Stats_Atleast1_DF.shape

(76, 14)

In [55]:
GCE_PerGene_Stats_Atleast1_DF.head(1)

          Chrom   Start     End Strand H37rv_GeneID   Symbol Feature           Functional_Category Is_Pseudogene                              Product PEandPPE_Subfamily ExcludedGroup_Category  pGCE_Count  CenterOfRegion
98  NC_000962.3  102814  103663      -      Rv0093c  Rv0093c     CDS  cell wall and cell processes            No  Probable conserved membrane protein                NaN            NotExcluded           1        103238.5

#### H37Rv - Per HHR

In [56]:
WGA151_Gubbins_FilePath_Dict["EventsPer_HHR_H37Rv_TSV"]

'/n/data1/hms/dbmi/farhat/mm774/Projects/Mtb_WGA_Analysis_V8/240923.WGA151CI.V8/Gubbins_v321_ExtSearch_SW_MS4_mpileup_SNVs_10AmbThresh/Gubbins.H37Rv.EventsPerMergedHomologousRegion.tsv'

In [57]:
!ls -alh /n/data1/hms/dbmi/farhat/mm774/Projects/Mtb_WGA_Analysis_V8/240923.WGA151CI.V8/Gubbins_v321_ExtSearch_SW_MS4_mpileup_SNVs_10AmbThresh/Gubbins.H37Rv.EventsPerMergedHomologousRegion.tsv

-rw-r--r-- 1 mm774 hpc_farhat 23K Aug  2 20:09 /n/data1/hms/dbmi/farhat/mm774/Projects/Mtb_WGA_Analysis_V8/240923.WGA151CI.V8/Gubbins_v321_ExtSearch_SW_MS4_mpileup_SNVs_10AmbThresh/Gubbins.H37Rv.EventsPerMergedHomologousRegion.tsv

In [58]:
GCE_PerHHR_Stats_DF = pd.read_csv(WGA151_Gubbins_FilePath_Dict["EventsPer_HHR_H37Rv_TSV"], sep = "\t")

In [59]:
GCE_PerHHR_Stats_DF.head(3)

   HmRegion_Num          Chr   Start     End  Num_Ovrlap_Hm_Regions    Center  Length  num_HomologRegions_NonOvrlap  num_HomologRegions_NonOvrlap_MinSeqID99  num_HomologRegions_NonOvrlap_MinSeqID100    Overlap_Genes  Overlap_TE  Contains_Esx  Contains_PEPPE  Contains_REP13E12  NoOverlap_Wi_PEPPE_Esx_13E12_Genes    HmRegionID  pGCE_Count  CenterOfRegion
0             0  NC_000962.3   80184   80523                      1   80353.5     339                             1                                        1                                         1           Rv0071           0         False           False              False                                True  HmRegion_000           0         80353.5
1             1  NC_000962.3   80623   82664                      1   81643.5    2041                             1                                        1                                         1    Rv0072,Rv0073           0         False           False              False                                True  HmRegion_001           0         81643.5
2             2  NC_000962.3  103705  105130                      2  104417.5    1425                             2                                        2                                         2  Rv0094c,Rv0095c           0         False           False               True                               False  HmRegion_002          31        104417.5

In [60]:

PerHHR_SelectCol = ["HmRegionID", "Overlap_Genes", "Chr", "Start", "End", "Center", "Length", "pGCE_Count", "Overlap_GC_EventIDs" ] 
PerHHR_SelectCol = ["HmRegionID", "Overlap_Genes", "Chr", "Start", "End", "Center", "Length", "pGCE_Count"] 

GCE_PerHHR_Stats_V2_DF = GCE_PerHHR_Stats_DF[PerHHR_SelectCol]
GCE_PerHHR_Stats_V2_DF.shape

(197, 8)

In [61]:
GCE_PerHHR_Stats_V2_DF.sort_values("pGCE_Count", ascending=False).head(4)

       HmRegionID     Overlap_Genes          Chr    Start      End     Center  Length  pGCE_Count
2    HmRegion_002   Rv0094c,Rv0095c  NC_000962.3   103705   105130   104417.5    1425          31
64   HmRegion_064  PE_PGRS28,Rv1453  NC_000962.3  1636705  1639561  1638133.0    2856          21
63   HmRegion_063         PE_PGRS27  NC_000962.3  1633310  1634790  1634050.0    1480          19
177  HmRegion_177     Rv3466,Rv3467  NC_000962.3  3883535  3884921  3884228.0    1386          17

In [62]:
GCE_PerHHR_Stats_DF.head()

   HmRegion_Num          Chr   Start     End  Num_Ovrlap_Hm_Regions    Center  Length  num_HomologRegions_NonOvrlap  num_HomologRegions_NonOvrlap_MinSeqID99  num_HomologRegions_NonOvrlap_MinSeqID100    Overlap_Genes  Overlap_TE  Contains_Esx  Contains_PEPPE  Contains_REP13E12  NoOverlap_Wi_PEPPE_Esx_13E12_Genes    HmRegionID  pGCE_Count  CenterOfRegion
0             0  NC_000962.3   80184   80523                      1   80353.5     339                             1                                        1                                         1           Rv0071           0         False           False              False                                True  HmRegion_000           0         80353.5
1             1  NC_000962.3   80623   82664                      1   81643.5    2041                             1                                        1                                         1    Rv0072,Rv0073           0         False           False              False                                True  HmRegion_001           0         81643.5
2             2  NC_000962.3  103705  105130                      2  104417.5    1425                             2                                        2                                         2  Rv0094c,Rv0095c           0         False           False               True                               False  HmRegion_002          31        104417.5
3             3  NC_000962.3  149571  149808                      1  149689.5     237                             1                                        1                                         1         PE_PGRS2           0         False            True              False                               False  HmRegion_003           0        149689.5
4             4  NC_000962.3  177203  177447                      1  177325.0     244                             1                                        1                                         1              NaN           0         False           False              False                                True  HmRegion_004           0        177325.0

In [63]:
GCE_PerHHR_Stats_DF.query("num_HomologRegions_NonOvrlap_MinSeqID99 >= 1").shape

(158, 19)

In [64]:
GCE_PerHHR_NonPerfRepeat_Stats_DF = GCE_PerHHR_Stats_DF.query("num_HomologRegions_NonOvrlap_MinSeqID99 >= 1")
GCE_PerHHR_NonPerfRepeat_Stats_DF.shape

(158, 19)

In [65]:
GCE_PerHHR_Stats_DF.shape

(197, 19)

### Create DF of HHRs w/ more than 1 GC Event detected

In [66]:
GCE_PerHHR_WiOvrLapGCE_Stats_DF = GCE_PerHHR_Stats_DF.query("pGCE_Count > 0")

GCE_PerHHR_WiOvrLapGCE_Stats_DF.shape

(54, 19)

In [67]:
GCE_PerHHR_NonPerfRepeat_Stats_DF.head()

   HmRegion_Num          Chr   Start     End  Num_Ovrlap_Hm_Regions    Center  Length  num_HomologRegions_NonOvrlap  num_HomologRegions_NonOvrlap_MinSeqID99  num_HomologRegions_NonOvrlap_MinSeqID100    Overlap_Genes  Overlap_TE  Contains_Esx  Contains_PEPPE  Contains_REP13E12  NoOverlap_Wi_PEPPE_Esx_13E12_Genes    HmRegionID  pGCE_Count  CenterOfRegion
0             0  NC_000962.3   80184   80523                      1   80353.5     339                             1                                        1                                         1           Rv0071           0         False           False              False                                True  HmRegion_000           0         80353.5
1             1  NC_000962.3   80623   82664                      1   81643.5    2041                             1                                        1                                         1    Rv0072,Rv0073           0         False           False              False                                True  HmRegion_001           0         81643.5
2             2  NC_000962.3  103705  105130                      2  104417.5    1425                             2                                        2                                         2  Rv0094c,Rv0095c           0         False           False               True                               False  HmRegion_002          31        104417.5
3             3  NC_000962.3  149571  149808                      1  149689.5     237                             1                                        1                                         1         PE_PGRS2           0         False            True              False                               False  HmRegion_003           0        149689.5
4             4  NC_000962.3  177203  177447                      1  177325.0     244                             1                                        1                                         1              NaN           0         False           False              False                                True  HmRegion_004           0        177325.0

In [68]:
GCE_PerHHR_WiOvrLapGCE_Stats_DF.query("num_HomologRegions_NonOvrlap_MinSeqID99 >= 1").shape

(54, 19)

In [69]:
GCE_PerHHR_WiOvrLapGCE_Stats_DF.query("num_HomologRegions_NonOvrlap_MinSeqID99 == 0").shape

(0, 19)

## Parse Gubbins ASR SNP files (w/ Codon Variant Annotations)

In [70]:
Gub_SNPs_V2_DF = pd.read_csv(WGA151_Gubbins_FilePath_Dict["BaseAncRec_All_WiCDS_Epitope_Info_TSV"],
                                         sep = "\t")

Gub_SNPs_V2_DF.shape

(26508, 23)

In [71]:
Gub_SNPs_V2_DF.head()

   Pos_1based Parent_Node Child_Node Parent_Call Child_Call EventID  Pos_0based        Chrom  NumHmOvrlap  HmOvrlap RegionType  N_OverlapGenes  Symbol Strand  Gene_Pos_0  Codon  Codon_Pos Ref_AA Mut_AA  Start    End   Lineage  N_Epitopes_Overlap
0        1088      Node_1      N1176           G          A     NaN        1087  NC_000962.3            0         0        Unq               1    dnaA      +      1087.0  363.0        2.0      S      N   1087   1088  lineage5                   0
1       10321      Node_1      N1176           C          T     NaN       10320  NC_000962.3            0         0        Unq               1  Rv0007      +       407.0  136.0        3.0    NaN    NaN  10320  10321  lineage5                   0
2       11846      Node_1      N1176           C          G     NaN       11845  NC_000962.3            0         0        Unq               0     NaN    NaN         NaN    NaN        NaN    NaN    NaN  11845  11846  lineage5                   0
3       16515      Node_1      N1176           T          C     NaN       16514  NC_000962.3            0         0        Unq               1    pknB      -       955.0  319.0        2.0      D      G  16514  16515  lineage5                   0
4       34063      Node_1      N1176           C          T     NaN       34062  NC_000962.3            0         0        Unq               0     NaN    NaN         NaN    NaN        NaN    NaN    NaN  34062  34063  lineage5                   0

### Subset Gubbins ASR SNPs (V2 Table) into groups of interest

In [72]:
Gub_SNPs_NSMutOnly_DF       = Gub_SNPs_V2_DF[~Gub_SNPs_V2_DF["Mut_AA"].isna()].query("Ref_AA != Mut_AA")

Gub_SNPs_NSMutIn_pGCE_DF    = Gub_SNPs_NSMutOnly_DF.query("EventID != 'None'")

Gub_SNPs_NSMutIn_mGCE_DF    = Gub_SNPs_NSMutOnly_DF[ Gub_SNPs_NSMutOnly_DF["EventID"].isin(mGCE_EventIDs) ]

Gub_SNPs_NSMutInEpitope_DF  = Gub_SNPs_NSMutOnly_DF.query(" N_Epitopes_Overlap > 0 ")

# Analysis Section

# Part 1: Measure enrichment of GCEs in antigens versus non-antigens in the HH Regions

## First organize the key stats

In [73]:
Antigen_GCandMutFreqStats_DF.shape

(53, 38)

In [74]:
Genes_GCandMutFreqStats_DF.shape

(3841, 36)

In [75]:
Antigen_GCandMutFreqStats_DF["Length_WiPosEpitope"].sum()

9117

#### How much of the genome is an epitope genome-wide (HHR + Unique)

In [76]:
Antigen_GCandMutFreqStats_DF["Length_WiPosEpitope"].sum()

9117

#### How much of genome is an epitope in an HHR?

In [77]:
Antigen_GCandMutFreqStats_DF.query("AntigenLVL2_And_HHR_Comb == 'Antigen-HHR'")["Length_WiPosEpitope"].sum()

4395

#### How much of genome is an HHR?

In [78]:
Rv_HHR_DF["Length"].sum()

257094

In [79]:
4411532

4411532

### How many total pGCEs? (`324` Total)

In [80]:
pGCE_DF.shape

(324, 46)

### How many total pGCEs that cause NS Mut? (`280`)

In [81]:
pGCE_DF.query("N_NS_Mut > 0").shape

(280, 46)

### How many total pGCEs in HHRs? (`295`)

In [82]:
pGCE_DF.query("NumHmTargets > 0").shape

(295, 46)

### How many total pGCEs w/ NS Muts + in HHRs? (`254`)

In [83]:
pGCE_DF.query("(N_NS_Mut > 0) & (NumHmTargets > 0)").shape

(254, 46)

In [84]:
254 / 324

0.7839506172839507

In [85]:
pGCE_DF.query("(NumHmTargets > 0) & (Overlap_WiAntigenLVL2Gene == True)").shape

(48, 46)

In [86]:
pGCE_DF.query("(N_NS_Mut > 0) & (NumHmTargets > 0) & (Overlap_WiAntigenLVL2Gene == True)").shape

(42, 46)

In [87]:
pGCE_DF.head()

       seqname   source feature  start_1based  end_1based  score strand Parent_Node Child_Node  neg_log_likelihood  snp_count                                          taxa_List  start_0based   Lineage  CenterOfRegion    Overlap_Genes Overlap_Gene_RvIDs  Contains_Esx  Contains_PEPPE  Contains_REP13E12  NoOverlap_Wi_PEPPE_Esx_13E12_Genes    EventID  EventLen  IsTermNode  NumHmTargets  NumHm_AtMaxKmerMatch                        Top_KmerMatch_HomologTarIDs   Top_KmerMatch_HomologGeneIDs  Max_KmerMatch_ToHm  DistToHm_TopKmatch  TotalKmers_Eval  NumHm_AtMaxSNPMatch                         Top_SNPMatch_HomologTarIDs    Top_SNPMatch_HomologGeneIDs  Max_SNPMatch_ToHm  DistToHm_TopSNPmatch  Freq_SNP_FoundInAnyPR  MaxJC_ToAnyRvGene                GeneIDs_MaxJC  NGenesIDs_MaxJC  NUnqHashes_Event  Overlap_WiAntigenLVL2Gene  N_NS_Mut  N_EpiMutated_By_GCE  N_NegPepMutated_By_GCE EpitopeIDs_NSMutByEvent
0  NC_000962.3  GUBBINS     CDS        103600      104478    0.0      .    Node_148   Node_133         1737.432787         10  ['mada_2-31', 'mada_1-41', 'MT_0080', 'mada_10...        103599       NaN        104038.5  Rv0093c,Rv0094c    Rv0093c,Rv0094c         False           False               True                               False  Event_001       879       False             2                     2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467              0.8608                 NaN               79                    2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467                0.0                   NaN                    0.0             0.8608        ['Rv3467', 'Rv0094c']              2.0              79.0                      False         0                    0                       0                       .
1  NC_000962.3  GUBBINS     CDS        103676      103930    0.0      .      Node_3      N1177         1950.228311          5                                          ['N1177']        103675  lineage6        103802.5          Rv0094c            Rv0094c         False           False               True                               False  Event_002       255        True             2                     2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467              0.0000                 NaN               46                    2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467                0.0                   NaN                    0.0             0.0870          ['prpC', 'Rv2508c']              2.0              46.0                      False         4                    0                       0                       .
2  NC_000962.3  GUBBINS     CDS        103823      103846    0.0      .    Node_146      N0153         1944.165722          4                                          ['N0153']        103822  lineage1        103834.0          Rv0094c            Rv0094c         False           False               True                               False  Event_003        24        True             2                     2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467              0.0000                 NaN               28                    2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467                0.0                   NaN                    0.0             0.1429  ['rplX', 'mesT', 'Rv1148c']              3.0              28.0                      False         4                    0                       0                       .
3  NC_000962.3  GUBBINS     CDS        103823      104065    0.0      .    Node_134     R27252         2067.461166          6                                         ['R27252']        103822  lineage1        103943.5          Rv0094c            Rv0094c         False           False               True                               False  Event_004       243        True             2                     2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467              0.0000                 NaN               50                    2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467                0.0                   NaN                    0.0             0.0800  ['rplX', 'mesT', 'Rv1148c']              3.0              50.0                      False         5                    0                       0                       .
4  NC_000962.3  GUBBINS     CDS        103823      104712    0.0      .      Node_4     Node_3         3155.350126          7                        ['N1177', 'N1202', 'N0091']        103822  lineage6        104267.0          Rv0094c            Rv0094c         False           False               True                               False  Event_005       890       False             2                     2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467              0.1528                 NaN               72                    2  Rv1587c,Rv1588c-H37Rv-1788513-1789865-Rv3466,R...  Rv1587c,Rv1588c-Rv3466,Rv3467                0.0                   NaN                    0.0             0.1528        ['Rv3466', 'Rv1588c']              2.0              72.0                      False         1                    0                       0                       .

In [88]:
GCE_PerHHR_WiOvrLapGCE_Stats_DF.shape

(54, 19)

In [89]:
GCE_PerHHR_Stats_V2_DF.shape

(197, 8)

In [90]:
GCE_PerHHR_Stats_V2_DF.head()

     HmRegionID    Overlap_Genes          Chr   Start     End    Center  Length  pGCE_Count
0  HmRegion_000           Rv0071  NC_000962.3   80184   80523   80353.5     339           0
1  HmRegion_001    Rv0072,Rv0073  NC_000962.3   80623   82664   81643.5    2041           0
2  HmRegion_002  Rv0094c,Rv0095c  NC_000962.3  103705  105130  104417.5    1425          31
3  HmRegion_003         PE_PGRS2  NC_000962.3  149571  149808  149689.5     237           0
4  HmRegion_004              NaN  NC_000962.3  177203  177447  177325.0     244           0

# Extras